version: '3.8'
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ../mysql-dump:/docker-entrypoint-initdb.d