version: '3.3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ../mysql-dump:/docker-entrypoint-initdb.d

  app:
    image: api:0.1.0
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB=root:password@(mysql:3306)/library
      - GIN_MODE=release
    depends_on:
      - mysql