name: golang-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: make lint
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit tests.
        run: make test
  
  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build
  
  docker:
    name: Docker
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.14

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Build docker
        run: docker build -t api:0.1.0 . 

